# Generated by Django 4.2.15 on 2024-08-18 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("apk_file_path", models.FileField(upload_to="apks/")),
                (
                    "first_screen_screenshot_path",
                    models.ImageField(upload_to="screenshots/"),
                ),
                (
                    "second_screen_screenshot_path",
                    models.ImageField(upload_to="screenshots/"),
                ),
                ("video_recording_path", models.FileField(upload_to="videos/")),
                ("ui_hierarchy", models.TextField()),
                ("screen_changed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_date", models.DateTimeField(auto_now_add=True)),
                ("result", models.CharField(max_length=100)),
                ("logs_path", models.FileField(upload_to="logs/")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="apk_manager.app",
                    ),
                ),
            ],
        ),
    ]
